### ISSUE TITLE
macOS: My Vita3K.app instantly closes!

### ISSUE THREAD

**Issue by 1whatleytay** [Vita3K/Vita3K#392] opened 2019-01-26 16:30 UTC
**Steps to reproduce:** Double click the .app file on macOS. You can get your .app file from your development environment on the website, worked both ways for me.
**What happens:** It instantly closes! How rude!
**What I think should happen:** It works, starts up, and I can play my pre-installed games without any workarounds.

**Workarounds:** It's not impossible to start Vita3K though, you'll just have to try something different.

- Right click on Vita3K and click "Show Package Contents". Then, navigate Contents -> MacOS and double click on Vita3K. It'll open a terminal and run perfectly!
<img width="378" alt="screen shot 2019-01-26 at 11 05 16 am" src="https://user-images.githubusercontent.com/32211852/51789779-9c072d00-215a-11e9-954d-4679410f19d0.png">
<img width="881" alt="screen shot 2019-01-26 at 11 05 38 am" src="https://user-images.githubusercontent.com/32211852/51789789-ba6d2880-215a-11e9-81e0-67411730638a.png">

- Opening it in your development environment directly seems to work fine as well, wether it be XCode or Clion.
- Dropping your Vita3K executable in the terminal directly also does the trick!

**What the heck is going wrong!?** I was having difficulty properly debugging this bug (or at least, I hope it is) because in every development environment Vita3K worked fine. I tried opening it in Instruments too, but it started and worked normally.
**My best guess:** I'm thinking it has something to do with Vita3K's logging. Development environments and the workarounds above all open terminals which Vita3K uses to print, but directly opening the .app does not. Maybe its hitting some bad access?

If this is expected behaviour, then feel free to close this issue. It might be nice to clear this up in #info-faq though. This same issue was encountered by IOI#6476 in discord, so I thought I would at least say something here.

**Comment by johnothwolo** [comment] 2019-01-31 14:01
I can confirm that happens on the latest nightly build on Mojave 10.14.2.

**Comment by VelocityRa** [comment] 2019-01-31 21:12
@1whatleytay You can try adding `raise(SIGTRAP);` line by line to see where it fails.

Also I'm assuming you've tried running it by attaching debuggers to the appveyor builds, correct? As opposed to building + running Debug builds from the environment. If not, try it.

**Comment by 1whatleytay** [comment] 2019-01-31 21:36
I just double checked, the when I try to run the Travis build with Instruments it works fine. Just double clicking it makes it crash... how irritating!

I'll try dropping `raise(SIGTRAP);`s everywhere in a bit. Thanks for the help.

**Comment by VelocityRa** [comment] 2019-01-31 21:41
Signal behaviour varies between systems so try other signals as well if TRAP doesn't work. Initially put it first thing in main (so that it has to run first) and find out which signal results in different behaviour than instant closing.

**Comment by chargeflux** [comment] 2019-05-11 14:42
I wonder if it has to do with App Translocation. If you extract and launch the app from the zip file in your ~/Downloads folder it will probably fail. Essentially macOS moves the extracted app bundle from the zip file into a read-only directory and executes it from there. When Vita3K tries create the directory in `Vita3K.app/Contents/Resources/shaderlog` in the app directory, it crashes since the location is read-only. 

The solution is to either create a signed DMG or detect if the location it launches from is read-only and prompt the user to move to `~/Applications`.

https://lapcatsoftware.com/articles/app-translocation.html

**Comment by Aphrodites1995** [comment] 2019-06-16 07:01
I encountered the same problem, and I solved it by moving Vita3K to the Applications folder. Hope it works for you!

**Comment by AbandonedCart** [comment] 2020-11-23 21:49
There is still an instant crash in the nightly build (downloaded 11/23 at 1:45 PST)
Here is the log that it attempts to send Apple. Looks like a Discord integration issue.

```
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/discord_game_sdk.dylib
  Referenced from: /Applications/Vita3K.app/Contents/MacOS/Vita3K
  Reason: image not found
```

**Comment by johnothwolo** [comment] 2020-11-24 18:05
I believe this can be solved by adding the following to the CmakeLists.txt:

`	set_target_properties(vita3k PROPERTIES LINK_FLAGS "-rpath @executable_path/Resources/")
`

according to [this](https://blog.krzyzanowskim.com/2018/12/05/rpath-what/)

**Comment by negamalireid** [comment] 2021-02-11 21:30
Hey, I still cant open the app on macos. 

The file shows as a textfile, not a unix executable, and running that file in terminal only opens it in text.

**Comment by johnothwolo** [comment] 2021-04-12 04:16
@negamalireid  The problem might here [a3aa6a6](https://github.com/Vita3K/Vita3K/commit/c9e25ec8904982ca662340700597266e30804ef3#diff-c2714bb72c4019858eab3c81e9453c72443e347bb1b62ce9b962ef188069019bR135-R139). Though I don't see how a conditional statement could've messed things up.

**Comment by strikersh** [comment] 2021-04-12 06:44
It shouldn't impact the runtime this is called while linking and discord rich presence is enabled by default

**Comment by shinra-electric** [comment] 2023-07-21 07:46
Is this still an issue? 

Can probably be closed....

**Closed** 2023-07-21 09:16 UTC
Labels: bug, mac
