### ISSUE TITLE
[BUG]: Vita3K cannot execute PCSG00610 after lastest memoey leak update

### ISSUE THREAD

**Issue by DarXtorm666** [Vita3K/Vita3K#3284] opened 2024-04-27 09:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

v0.2.0 3596-418f2343

### Description of Issue

![image](https://github.com/Vita3K/Vita3K/assets/59574376/17d4654b-e886-4d2f-af11-ab2faab5466a)

### Expected Behavior

before this memory leak update, I can play this game normally.

### Reproduction Steps

get the latest Vita3K, then just run this game.

### Log File

[vita3k.log](https://github.com/Vita3K/Vita3K/files/15137734/vita3k.log)

### System Configuration

CPU: Intel(R) Core(TM) i5-14400F | 10 Threads | 2.496 GHz
GPU/Driver:  NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
RAM: Available ram memory: 16194 MiB
OS: Microsoft Windows 10 Professional (build 19045)

**Comment by DarXtorm666** [comment] 2024-04-27 10:27
update:
I can run this game normally with release#3594, and I guess #3595 is also OK because I played this game a day ago.

**Comment by bookmist** [comment] 2024-04-27 11:44
It may depends of dump type (here - maidump) not the game itself. I'm going to check with other maidump game.

**Comment by bookmist** [comment] 2024-05-03 17:15
I checked this on latest release (https://github.com/Vita3K/Vita3K/commit/418f2343948bc4f4bfa1f6c098dd95cf6e4b971e). nonpdrm dump of PCSG00610 starts and shows start screen. other maidump games also start and show start screen. Sorry, I can't reproduce this bug.

**Comment by DarXtorm666** [comment] 2024-05-05 07:32
It's fine, I used the #3594( 49480f8 ) and it could work...
Just keep a record for it and I'll try newer release one afterwards.

**Comment by scribam** [comment] 2024-08-22 17:23
@DarXtorm666 is it still an issue with the latest build?

**Comment by DarXtorm666** [comment] 2024-08-23 08:41
Hi @scribam ,

I try the latest: v0.2.0 3630-1c315b1f on my another computer,
then execute PCSG00610 and Vita3K will be shutdown with this error messgae:
![v33k_err](https://github.com/user-attachments/assets/95b24630-7d36-4e6c-8af8-215103223d6b)

On the other hand, I use v0.1.6 3129-e9969a11 that could execute PCSG00610 normally.

**Comment by scribam** [comment] 2024-08-23 17:39
@DarXtorm666 is it a maidump game?

**Comment by DarXtorm666** [comment] 2024-08-23 18:42
Hi @scribam,

Yeah, it seems maidump game.
I search the keyword "maidump" you mentioned, then I find a document that tells me should rename the eboot_origin.bin to eboot.bin and put it to game root directory, otherwise the game cannot be loaded.
And after I do this,  the game will be executed normally.

**Comment by scribam** [comment] 2024-08-23 19:56
@DarXtorm666 so is it working correctly now?

Maidump games are unstable, check the "Dumping Games" section at https://vita3k.org/quickstart.html for other ways to dump your games

**Comment by DarXtorm666** [comment] 2024-08-24 05:29
@scribam 
Yeah it works correctly now.
Got it, I'll check it.

**Comment by scribam** [comment] 2024-08-24 07:12
Issue solved, closing

**Closed by scribam** 2024-08-24 07:12 UTC
Labels: bug
