### ISSUE TITLE
WipEout 2048 [PCSA00015] - FPS drop to 1 when starting a race

### ISSUE THREAD

**Issue by NightK15** [Vita3K/Vita3K#3157] opened 2023-12-29 15:15 UTC
Since vita3k-a49d8923 (PR #3140 - Action 9461), the game now seems to be dropping FPS to 1 randomly (but quite often) when entering a race. This issue can be reproduced by entering a race from any mode, if it doesn't trigger, try switching maps. I tried changing almost every setting with no luck.

These are my specs:
CPU: Intel Core i5-12400F
GPU: AMD Radeon RX 6700 XT
RAM: 32 GB

Here are some comparison screenshots between Action 9461 ( #3140) and Action 9460 (#3141):
**Action 9460**
![Captura de pantalla 2023-12-29 105746](https://github.com/Vita3K/Vita3K/assets/31520555/6b743831-486b-41ed-8296-1fda34041198)
**Action 9461**
![Captura de pantalla 2023-12-29 110241](https://github.com/Vita3K/Vita3K/assets/31520555/ceee0ad2-6f1d-428a-9431-e8a085744791)
**Action 9460**
![Captura de pantalla 2023-12-29 105915](https://github.com/Vita3K/Vita3K/assets/31520555/00fbc448-d6e6-4334-b1bd-07277791f885)
**Action 9461**
![Captura de pantalla 2023-12-29 110413](https://github.com/Vita3K/Vita3K/assets/31520555/90810263-2ee7-49e6-99bf-94d8e7032b33)

Additional info: 
When clearing shaders in 9461, you can "choose" the mode you want to run properly. So if I clear the shaders and start a 2048 race, it will likely run properly most 2048 races, but HD/Fury will be stuck at 1 FPS. At least, it happens to me.

**Action 9460**
![Captura de pantalla 2023-12-29 105952](https://github.com/Vita3K/Vita3K/assets/31520555/d060bef6-ee39-48ca-953d-312b68384ad1)
**Action 9461, after clearing shaders**
![Captura de pantalla 2023-12-29 110744](https://github.com/Vita3K/Vita3K/assets/31520555/5c52f9e9-a01f-4c18-89ca-a918b8b0bb73)

**Comment by alexandar76** [comment] 2023-12-30 14:22
With the latest build 3529 framerate is droping in some games from 60 fps to 1 fps. Where to download older release 3527, 3528?

**Comment by poudink** [comment] 2023-12-31 01:14
You can download the last working version here: https://github.com/Vita3K/Vita3K/actions/runs/7322770106

This is a massive regression which makes half of the Vita library completely unplayable (unless I'm just massively unlucky, because this broke most of the games I have). Can this be corrected soon, please? It's been five days since the PR was merged and half of my games are completely broken. The only thing in common between my setup (Steam Deck) and OP's is the AMD GPU (with completely different drivers), so I assume this isn't platform-specific.

**Comment by nn9dev** [comment] 2023-12-31 01:46
> This is a massive regression which makes half of the Vita library completely unplayable (unless I'm just massively unlucky, because this broke most of the games I have). Can this be corrected soon, please?

From my understanding, nobody has reported this until now, so if you experience these moving forward it would be a great help to notify some of us (or at least me, when there's an issue I annoy everyone until something happens).

Funnily enough I was having a headache earlier this week where Gravity Rush wouldn't boot, and now that you mention it this PR seems to be the culprit. Are you in the discord? It would be good to correspond with you so that I can corroborate some of your claims and compile a report for Macdu to look at.

**Closed** 2023-12-31 15:38 UTC
