### ISSUE TITLE
texture broken 

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1044] opened 2020-12-10 09:21 UTC
after some test, is hmm complicated, diferent girl apear on home, and some is good rended, and some other is broken

texture get spitted and so broken on this game, maybe on also other

On last master
- Girl broken
![image](https://user-images.githubusercontent.com/5261759/101750463-52febe80-3acf-11eb-868e-777ca68a75d8.png)

- Girl good
![image](https://cdn.discordapp.com/attachments/442344583293304833/786538186732994570/unknown.png)

**Comment by scribam** [comment] 2020-12-18 08:30
Some WIP screenshots 🙂 

![Capture](https://user-images.githubusercontent.com/25406440/102592224-751dbf80-4113-11eb-84be-56a77b02ad98.PNG)

![Capture2](https://user-images.githubusercontent.com/25406440/102592240-7bac3700-4113-11eb-837d-7ef7443f465e.PNG)

![Capture3](https://user-images.githubusercontent.com/25406440/102592332-9bdbf600-4113-11eb-9044-6333316b57dc.PNG)

Got a regression for the text at the bottom 🤔

**Comment by Zangetsu38** [comment] 2020-12-18 10:01
Oh goid works

**Comment by scribam** [comment] 2020-12-18 16:46
Bottom fixed, time for regressions testing with other games now

![Capture](https://user-images.githubusercontent.com/25406440/102639137-e3d13c00-4158-11eb-9d28-f5f9ba6a8e2f.PNG)

**Comment by Zangetsu38** [comment] 2020-12-18 16:53
Ignore this girl, look my screen this girl and onenothrr is’good allez-y on Master ^^

**Comment by Zangetsu38** [comment] 2020-12-18 16:56
Oh good works

**Comment by Zangetsu38** [comment] 2020-12-19 16:05
fixed by #1048

**Comment by scribam** [comment] 2020-12-19 18:03
Are you sure the textures are fixed by #1048? Because it doesn't work for me. I didn't take my screenshots with #1048.

**Comment by Zangetsu38** [comment] 2020-12-19 22:14
no sorry mistake lol random texture works have trolled me

**Closed** 2020-12-20 17:10 UTC
