### ISSUE TITLE
(Steam Deck) Game crashes when DualShock 4 is connected without Steam Input

### ISSUE THREAD

**Issue by Earleybyrd** [Vita3K/Vita3K#3019] opened 2023-10-23 19:05 UTC
Attempting to play Gravity Rush and have had no issues playing in handheld. (The Deck’s gyroscope doesn’t work, but as far as I understand, it simply isn’t supported and that’s expected)

Playing with a DS4 controller also works “fine”, but Steam Input overrides the native touchpad and gyroscope support. When disabling Steam Input and having Vita3K handle the controller natively, the game crashes directly after the shaders compile.

I know that Vita3K is properly recognizing the controller. I can go in desktop mode and see It listed under Vita3K’s “controller” tab, and I changed the DS4 light color so that I could know when the controller’s recognized. It is properly connected in the emulators UI, and when games are being launched (during shader compilation), in both desktop, and game mode. 

No matter what controller I am using, if a single DS4 without Steam Input is connected, games will not launch. Games still boot perfectly fine otherwise.

If this detail is important, I have installed Vita3K through Emudeck. I am on the latest build.

**Comment by nn9dev** [comment] 2023-10-23 19:45
On your Deck, how are you going about "disabling Steam Input"? Just closing Steam? I'm about to sit down and try and reproduce this issue, and I wanna be sure I have your steps exact.

**Comment by nn9dev** [comment] 2023-10-23 20:30
I was able to reproduce your issue. Unbeknownst to me, it seems like this issue has already been brought up and talked about. I am inconclusively concluding that this has to do with the Steam Deck's installed SDL2. I am on the latest Stable branch, as I assume you are, and running `sdl2-config --version` reports `2.24.1`. The offending function making Vita3K crash, `SDL_GameControllerGetSensorDataWithTimestamp`, was introduced in SDL version 2.26. 

I'm /ASSUMING/ that SDL will get a version bump with the release of SteamOS 3.5 (as with OpenSSL), but I don't know for certain since -- as I said -- I'm on Stable branch.

Assuming I HAVE gotten the cause correct in my limited testing, your possible solutions in my eyes are:
\ - Update to SteamOS 3.5 Preview on the Preview branch
\ - Unlock read-only rootfs and install a newer version of SDL
\ - Statically link SDL2 to Vita3K  and build it on Deck (which is likely more work than it's worth)

**Comment by Earleybyrd** [comment] 2023-10-23 22:25
Thank you for looking into it! Shame it’s such a hassle, though. 

For unrelated reasons I’ve already decided to simply wait for the public release of 3.5 considering all the issues I’m hearing from the preview branch, and how it may interfere with my current setup- but good to know it may fix this issue when that time comes.

And worst case scenario, I’ll look into updating SDL.

**Comment by nn9dev** [comment] 2023-10-24 02:59
> I’ve already decided to simply wait for the public release of 3.5 considering all the issues I’m hearing

I can't blame you for this. I'm doing the same, else I'd test for you. I'll keep an eye on it, but I assume you'll probably beat me to the punch on testing this again when 3.5 releases.

**Comment by Macdu** [comment] 2023-10-24 10:13
> I was able to reproduce your issue. Unbeknownst to me, it seems like this issue has already been brought up and talked about. I am inconclusively concluding that this has to do with the Steam Deck's installed SDL2. I am on the latest Stable branch, as I assume you are, and running `sdl2-config --version` reports `2.24.1`. The offending function making Vita3K crash, `SDL_GameControllerGetSensorDataWithTimestamp`, was introduced in SDL version 2.26.
> 
> I'm /ASSUMING/ that SDL will get a version bump with the release of SteamOS 3.5 (as with OpenSSL), but I don't know for certain since -- as I said -- I'm on Stable branch.
> 
> Assuming I HAVE gotten the cause correct in my limited testing, your possible solutions in my eyes are: - Update to SteamOS 3.5 Preview on the Preview branch - Unlock read-only rootfs and install a newer version of SDL - Statically link SDL2 to Vita3K and build it on Deck (which is likely more work than it's worth)

If the issue is only with `SDL_GameControllerGetSensorDataWithTimestamp` I can write a quick workaround for it (only use it if the version of SDL used is at least 2.26).

**Comment by nn9dev** [comment] 2023-10-24 21:40
It's up to you. It'd probably be good so Deck users aren't completely left in the dark. Not sure if you can make gyro function without it (since I haven't looked at the gyro code) but if you can then definitely go for it.

**Comment by Earleybyrd** [comment] 2023-10-25 00:18
> > I was able to reproduce your issue. Unbeknownst to me, it seems like this issue has already been brought up and talked about. I am inconclusively concluding that this has to do with the Steam Deck's installed SDL2. I am on the latest Stable branch, as I assume you are, and running `sdl2-config --version` reports `2.24.1`. The offending function making Vita3K crash, `SDL_GameControllerGetSensorDataWithTimestamp`, was introduced in SDL version 2.26.
> > I'm /ASSUMING/ that SDL will get a version bump with the release of SteamOS 3.5 (as with OpenSSL), but I don't know for certain since -- as I said -- I'm on Stable branch.
> > Assuming I HAVE gotten the cause correct in my limited testing, your possible solutions in my eyes are: - Update to SteamOS 3.5 Preview on the Preview branch - Unlock read-only rootfs and install a newer version of SDL - Statically link SDL2 to Vita3K and build it on Deck (which is likely more work than it's worth)
> 
> If the issue is only with `SDL_GameControllerGetSensorDataWithTimestamp` I can write a quick workaround for it (only use it if the version of SDL used is at least 2.26).

All up to you, but that would be super appreciated! Would be great to see the deck become a viable device for playing gyro-dependent games.

**Closed** 2023-10-26 11:27 UTC
