### ISSUE TITLE
No way to save games progress...(check screen shots)

### ISSUE THREAD

**Issue by profizadi** [Vita3K/Vita3K#3167] opened 2024-01-02 08:06 UTC
There is no in game pause menu to see the save slots and save the game progress...
Almost all emulator have this option.
If you exit games and close the app, you will lose your progress...
Next time you enter the app, you can't see the continue button under the game you played before;  you will see the start button which start every thing from the beginning and you will lose your progress.
The thing we need and request is in the screenshot attached, Please add it.
Thanks🌹
![Screenshot_20240102-111518~2](https://github.com/Vita3K/Vita3K/assets/155423480/1eed7976-00a6-451e-9b36-6c5092e64ca4)
![Screenshot_20240102-111451~2](https://github.com/Vita3K/Vita3K/assets/155423480/b34843f4-d524-4f94-9d09-3fd9618196b8)
![Screenshot_20240102-111503](https://github.com/Vita3K/Vita3K/assets/155423480/52fec379-4f83-4f3c-a762-04091b31d402)

**Comment by surlup** [comment] 2024-01-02 09:34
> There is no in game pause menu to see the save slots and save the game progress... Almost all emulator have this option. If you exit games and close the app, you will lose your progress... Next time you enter the app, you can't see the continue button under the game you played before; you will see the start button which start every thing from the beginning and you will lose your progress. The thing we need and request is in the screenshot attached, Please add it. Thanks🌹 ![Screenshot_20240102-111518~2](https://private-user-images.githubusercontent.com/155423480/293649193-1eed7976-00a6-451e-9b36-6c5092e64ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MTkzLTFlZWQ3OTc2LTAwYTYtNDUxZS05YjM2LTZjNTA5MmU2NGNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWExOTE2ZWM4MGRkYzIwYjVhN2ZhMzVlZjBiZWU0NDdmNzVkYTgzYzMyODhhYTdjYmExMzViNWYxMzI4ZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sERmLnCNc6W7W2kLkNPuZGNFF7zYf34M5GY3voJVXEQ) ![Screenshot_20240102-111451~2](https://private-user-images.githubusercontent.com/155423480/293649211-b34843f4-d524-4f94-9d09-3fd9618196b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MjExLWIzNDg0M2Y0LWQ1MjQtNGY5NC05ZDA5LTNmZDk2MTgxOTZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTBlM2UwOGZmY2UyZjE3MThhNWQyYzA0ZDQ4MjI5NTMzOGM2ZjA5MWQ0MDVhZDUwMjZkZTNjMTgxYzZiYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PlPJ5h5boNb1OzuSu-Igp6J_nicctpGN1_sIYDpYx0A) ![Screenshot_20240102-111503](https://private-user-images.githubusercontent.com/155423480/293649229-52fec379-4f83-4f3c-a762-04091b31d402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MjI5LTUyZmVjMzc5LTRmODMtNGYzYy1hNzYyLTA0MDkxYjMxZDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmFkYWEzNDA1NzM1OTRkNTc2ZWVjZDkzYTFjNmRkMGYwN2UwMmVhMDk3NmE0ODgxY2RmOGRmYzRmNWU0Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8R_znn0INlhEHLVmF6y58nGn5YB10mTy8wJpUCWWGZk)

![snapshots-menu](https://github.com/Vita3K/Vita3K/assets/125713102/1ca2611a-52e4-41eb-95b1-e618ad0b95d7)
This means save state, right? I prefer snapshots (save state) like Xemu on the xbox emulator. Snapshots, also often called Save States, are a representation of the entire machine state which can be saved or restored at any time. With snapshots you can virtually eliminate the need to rely on in-game checkpoints to save your progress. Save a snapshot, and load it up again later and it's as if you had just kept it on playing. I took this from dev emu xemu..this is just a suggestion for Vita3k devlopers

**Comment by profizadi** [comment] 2024-01-02 17:54
> > There is no in game pause menu to see the save slots and save the game progress... Almost all emulator have this option. If you exit games and close the app, you will lose your progress... Next time you enter the app, you can't see the continue button under the game you played before; you will see the start button which start every thing from the beginning and you will lose your progress. The thing we need and request is in the screenshot attached, Please add it. Thanks🌹 ![Screenshot_20240102-111518~2](https://private-user-images.githubusercontent.com/155423480/293649193-1eed7976-00a6-451e-9b36-6c5092e64ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MTkzLTFlZWQ3OTc2LTAwYTYtNDUxZS05YjM2LTZjNTA5MmU2NGNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWExOTE2ZWM4MGRkYzIwYjVhN2ZhMzVlZjBiZWU0NDdmNzVkYTgzYzMyODhhYTdjYmExMzViNWYxMzI4ZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sERmLnCNc6W7W2kLkNPuZGNFF7zYf34M5GY3voJVXEQ) ![Screenshot_20240102-111451~2](https://private-user-images.githubusercontent.com/155423480/293649211-b34843f4-d524-4f94-9d09-3fd9618196b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MjExLWIzNDg0M2Y0LWQ1MjQtNGY5NC05ZDA5LTNmZDk2MTgxOTZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTBlM2UwOGZmY2UyZjE3MThhNWQyYzA0ZDQ4MjI5NTMzOGM2ZjA5MWQ0MDVhZDUwMjZkZTNjMTgxYzZiYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PlPJ5h5boNb1OzuSu-Igp6J_nicctpGN1_sIYDpYx0A) ![Screenshot_20240102-111503](https://private-user-images.githubusercontent.com/155423480/293649229-52fec379-4f83-4f3c-a762-04091b31d402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODgzMTQsIm5iZiI6MTcwNDE4ODAxNCwicGF0aCI6Ii8xNTU0MjM0ODAvMjkzNjQ5MjI5LTUyZmVjMzc5LTRmODMtNGYzYy1hNzYyLTA0MDkxYjMxZDQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwOTMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmFkYWEzNDA1NzM1OTRkNTc2ZWVjZDkzYTFjNmRkMGYwN2UwMmVhMDk3NmE0ODgxY2RmOGRmYzRmNWU0Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8R_znn0INlhEHLVmF6y58nGn5YB10mTy8wJpUCWWGZk)
> 
> ![snapshots-menu](https://private-user-images.githubusercontent.com/125713102/293662634-1ca2611a-52e4-41eb-95b1-e618ad0b95d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTc2NjIsIm5iZiI6MTcwNDIxNzM2MiwicGF0aCI6Ii8xMjU3MTMxMDIvMjkzNjYyNjM0LTFjYTI2MTFhLTUyZTQtNDFlYi05NWIxLWU2MThhZDBiOTVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzQyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjQ4ODRlYTQ4YmUyZjJjZTUwYjU4NmUwNjlmOTIwOTNhYTMzMTc2NjU0MTM2NTYwOTVmZGFlY2JiNjc5ODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lh-_gX00akl4ksdnyipIwiuNCPunWFTNx_yKCSMMUqM) This means save state, right? I prefer snapshots (save state) like Xemu on the xbox emulator. Snapshots, also often called Save States, are a representation of the entire machine state which can be saved or restored at any time. With snapshots you can virtually eliminate the need to rely on in-game checkpoints to save your progress. Save a snapshot, and load it up again later and it's as if you had just kept it on playing. I took this from dev emu xemu..this is just a suggestion for Vita3k devlopers

Yes! That's righ!👌🏻👌🏻
I don't know how emu xemu works but the most important thing is that being able play the game exactly from where you left the game.
It's very important for mobile emulators because you usually don't play a long time with your mobile and so many time other uses of phone makes you leave the game several times... Also you can not leave the mobile in game like a PC or game console.
Then it's necessary to be able to continue game from where you exit.😊

**Comment by Zangetsu38** [comment] 2024-01-02 18:44
Save state is just not yet implemented

**Comment by surlup** [comment] 2024-01-03 07:44
> Save state is just not yet implemented

If I may know why  mot yet Implemented?

**Comment by scribam** [comment] 2024-08-13 17:34
This issue is a duplicate of #2494

**Closed by scribam** 2024-08-13 17:34 UTC
